const $=s=>document.querySelector(s);let me,classes=[];
const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
async function getProfile(user){const {data,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;return data}
async function loadClasses(){const {data,error}=await sb.from('classes').select('*').order('name');if(error)throw error;return data||[]}
async function enterApp(user){me=await getProfile(user);if(!me.active)throw Error('Conta inativa');classes=await loadClasses();$('#login').hidden=true;$('#app').hidden=false;$('#usersTab').hidden=me.role!=='coordinator';await view('dashboard')}
async function boot(){const {data:{session},error}=await sb.auth.getSession();if(error){$('#loginError').textContent='Erro ao verificar sessão: '+error.message;return}if(!session)return;try{await enterApp(session.user)}catch(e){$('#loginError').textContent='Login realizado, mas o perfil não pôde ser carregado: '+(e?.message||e);await sb.auth.signOut()}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='Entrando...';const email=$('#email').value.trim();const password=$('#password').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){$('#loginError').textContent='Não foi possível entrar: '+error.message;return}try{await enterApp(data.user);$('#loginError').textContent=''}catch(err){$('#login').hidden=false;$('#app').hidden=true;$('#email').value=email;$('#password').value=password;$('#loginError').textContent='A senha foi aceita, mas houve erro ao carregar o perfil: '+(err?.message||err);await sb.auth.signOut()}};
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));
async function view(name){const c=$('#content');
if(name==='dashboard'){c.innerHTML=`<h2>Olá, ${esc(me.name)}</h2><div class="grid"><div class="stat"><b>${classes.length}</b><br>turmas disponíveis</div><div class="stat"><b>${me.role==='coordinator'?'Coordenação':'Professor(a)'}</b><br>perfil de acesso</div></div>`}
if(name==='essays'){const {data:rows,error}=await sb.from('essays').select('*').order('production_date',{ascending:false});if(error)throw error;c.innerHTML=`<h2>Propostas de redação</h2><p>Cadastre e acompanhe propostas ENEM e UECE.</p><table><tr><th>Tema</th><th>Modelo</th><th>Bimestre</th><th>Data</th></tr>${(rows||[]).map(r=>`<tr><td>${esc(r.theme)}</td><td>${esc(r.model)}</td><td>${r.bimester}º</td><td>${esc(r.production_date)}</td></tr>`).join('')}</table>`}
if(name==='scores'){c.innerHTML=`<h2>Lançamento de notas</h2><label>Turma<select id="classSelect"><option value="">Selecione</option>${classes.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><div id="students"></div>`;$('#classSelect').onchange=async e=>{if(!e.target.value){$('#students').innerHTML='';return}const {data:s,error}=await sb.from('students').select('id,call_number,enrollment,name,active').eq('class_id',e.target.value).eq('active',true).order('call_number');if(error){$('#students').innerHTML='<p class="error">Não foi possível carregar os alunos.</p>';return}$('#students').innerHTML=`<table><tr><th>Chamada</th><th>Aluno</th><th>Matrícula</th></tr>${(s||[]).map(x=>`<tr><td>${x.call_number}</td><td>${esc(x.name)}</td><td>${esc(x.enrollment||'')}</td></tr>`).join('')}</table>`}}
if(name==='users'){if(me.role!=='coordinator')return;const {data:rows,error}=await sb.from('profiles').select('name,email,role,active').order('name');if(error)throw error;c.innerHTML=`<h2>Professores</h2><table><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Situação</th></tr>${(rows||[]).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.email)}</td><td>${r.role==='coordinator'?'Coordenação':'Professor(a)'}</td><td>${r.active?'Ativo':'Bloqueado'}</td></tr>`).join('')}</table>`}}
}
boot();
